### ISSUE TITLE
버전관리에 불필요한 ".idea" 안올라오게 해주세요.

### ISSUE THREAD

**Issue by bestheroz** [ceaser501/SpringMavenProject#5]
.idea는 몇개는 프로젝트 설정에서 필요할수 있어요.
그러니 개인설정 파일만 안올라오게 해주시면 될거 같아요.

**Comment by ceaser501** [comment]
.gitignore 파일 확인 부탁드립니다. 원격저장소 파일은 삭제했고, 해당 .gitignore 파일 로컬 적용되어 앞으론 버전관리 대상에서 제외될 것입니다~
