### ISSUE TITLE
"web" 이라는 폴더의 위치는 의도하신 건가요?

### ISSUE THREAD

**Issue by bestheroz** [ceaser501/SpringMavenProject#7]
최상위에 존재하는 web 이라는 폴더 내용은 스프링에서
/src/main/webapp에 존재하는데 따로 최상위로 빼신 이유가 있을까요?

없으시면 스프링 기본대로도 세팅해보심이 어떠신지요?

**Comment by ceaser501** [comment]
별다른 이유는 없으며, 스프링 기본대로 /src/main밑에 web폴더로 위치 이동했습니다.

**Comment by bestheroz** [comment]
/src/main/web -> /src/main/webapp
